### ISSUE TITLE
Applifly

### ISSUE THREAD

**Issue by jeetthakkar54** [wimpywarlord/appliFLY#13] opened 2023-10-25 19:42 UTC
Stacktrace:
        GetHandleVerifier [0x00007FF712638EF2+54786]
        (No symbol) [0x00007FF7125A5612]
        (No symbol) [0x00007FF71245A64B]
        (No symbol) [0x00007FF71249B79C]
        (No symbol) [0x00007FF71249B91C]
        (No symbol) [0x00007FF7124D6D87]
        (No symbol) [0x00007FF7124BBEAF]
        (No symbol) [0x00007FF7124D4D02]
        (No symbol) [0x00007FF7124BBC43]
        (No symbol) [0x00007FF712490941]
        (No symbol) [0x00007FF712491B84]
        GetHandleVerifier [0x00007FF712987F52+3524194]
        GetHandleVerifier [0x00007FF7129DD800+3874576]
        GetHandleVerifier [0x00007FF7129D5D7F+3843215]
        GetHandleVerifier [0x00007FF7126D5086+694166]
        (No symbol) [0x00007FF7125B0A88]
        (No symbol) [0x00007FF7125ACA94]
        (No symbol) [0x00007FF7125ACBC2]
        (No symbol) [0x00007FF71259CC83]
        BaseThreadInitThunk [0x00007FFD8A93257D+29]
        RtlUserThreadStart [0x00007FFD8C0AAA78+40]

**Comment by wimpywarlord** [comment] 2023-10-26 03:42
Please consider re-running the script

Could you share at which step it failed

**Comment by jeetthakkar54** [comment] 2023-10-26 04:36
It failed when it clicked the search button to view the entire list of jobsSent from my iPhoneOn Oct 25, 2023, at 8:42 PM, Kshitij Dhyani ***@***.***> wrote:﻿
Please consider re-running the script
Could you share at which step it failed

**Comment by wimpywarlord** [comment] 2023-10-27 00:33
Did you check out this thread

https://github.com/wimpywarlord/appliFLY/issues/12

**Comment by wimpywarlord** [comment] 2023-12-13 15:41
Closing this since solved in the following thread https://github.com/wimpywarlord/appliFLY/issues/12

**Closed by wimpywarlord** 2023-12-13 15:41 UTC

**Comment by dhosuruj** [comment] 2023-12-30 15:50
Hey,
Am facing the same issue can you send me a google meet request when you are free, so we can sync up and resolve it?
Here is my mail: dhosuruj@asu.edu

**Comment by wimpywarlord** [comment] 2023-12-30 15:54
were you able to read the following thread https://github.com/wimpywarlord/appliFLY/issues/12

**Comment by wimpywarlord** [comment] 2023-12-30 15:55
I also want to inform you, that due to the disruption caused by this script, ASU portal has limited the traffic to only 10 applications a day

**Comment by dhosuruj** [comment] 2023-12-30 15:58
I did go through the thread, but got a bit confused with where I need to put chrome driver.

**Comment by dhosuruj** [comment] 2023-12-30 15:59
> I also want to inform you, that due to the disruption caused by this script, ASU portal has limited the traffic to only 10 applications a day

Still would like to try once, even if its 10

**Comment by wimpywarlord** [comment] 2023-12-30 16:53
You can place the chrome driver anywhere, just put the absolute path of stored location.

**Comment by wimpywarlord** [comment] 2023-12-30 16:55
Here is my calendar link: https://calendly.com/kshitijdhyani/60min
